project('mabi-shell', 'vala', default_options: ['warning_level=3'], version: '0.1')

gtk4_layer_shell_dep = dependency('gtk4-layer-shell-0')
gtk4_dep = dependency('gtk4')
astal4_dep = dependency('astal-4-4.0')
astalio_dep = dependency('astal-io-0.1')
astal_hyprland_dep = dependency('astal-hyprland-0.1')
astal_wp_dep = dependency('astal-wireplumber-0.1')
adw_dep = dependency('libadwaita-1')
gee_dep = dependency('gee-0.8')
json_glib_dep = dependency('json-glib-1.0')

subdir('shell')
